"""Add feedback messages table for conversation history

Revision ID: c236b2efde86
Revises: eef9efa5c0ef
Create Date: 2025-10-26 17:02:15.522445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c236b2efde86'
down_revision: Union[str, None] = 'eef9efa5c0ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedbacks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_messages_author_id'), 'feedback_messages', ['author_id'], unique=False)
    op.create_index(op.f('ix_feedback_messages_feedback_id'), 'feedback_messages', ['feedback_id'], unique=False)
    op.create_index(op.f('ix_feedback_messages_id'), 'feedback_messages', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_messages_is_admin'), 'feedback_messages', ['is_admin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_messages_is_admin'), table_name='feedback_messages')
    op.drop_index(op.f('ix_feedback_messages_id'), table_name='feedback_messages')
    op.drop_index(op.f('ix_feedback_messages_feedback_id'), table_name='feedback_messages')
    op.drop_index(op.f('ix_feedback_messages_author_id'), table_name='feedback_messages')
    op.drop_table('feedback_messages')
    # ### end Alembic commands ###
