"""Add subject field to feedbacks

Revision ID: eef9efa5c0ef
Revises: 76dc0ff5f204
Create Date: 2025-10-26 16:35:30.628668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eef9efa5c0ef'
down_revision: Union[str, None] = '76dc0ff5f204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('subject', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_feedbacks_subject'), 'feedbacks', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedbacks_subject'), table_name='feedbacks')
    op.drop_column('feedbacks', 'subject')
    # ### end Alembic commands ###
