"""Add waveform_data to lessons

Revision ID: 723011635b8b
Revises: c236b2efde86
Create Date: 2025-10-26 22:02:56.945222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '723011635b8b'
down_revision: Union[str, None] = 'c236b2efde86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('waveform_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'waveform_data')
    # ### end Alembic commands ###
