"""add_unique_constraints_to_content_and_teachers

Revision ID: fb6b2e951ff1
Revises: 2025_10_24_0548
Create Date: 2025-10-24 10:40:26.113552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb6b2e951ff1'
down_revision: Union[str, None] = '2025_10_24_0548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_book_author_name', 'book_authors', ['name'])
    op.create_unique_constraint('unique_book_per_author', 'books', ['name', 'author_id'])
    op.create_unique_constraint('unique_lesson_teacher_name', 'lesson_teachers', ['name'])
    op.create_unique_constraint('unique_theme_name', 'themes', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_theme_name', 'themes', type_='unique')
    op.drop_constraint('unique_lesson_teacher_name', 'lesson_teachers', type_='unique')
    op.drop_constraint('unique_book_per_author', 'books', type_='unique')
    op.drop_constraint('unique_book_author_name', 'book_authors', type_='unique')
    # ### end Alembic commands ###
